# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: nhsht

before:
  hooks:
    - go mod tidy
    # - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    # binary: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    no_unique_dist_dir: false
    targets:
      - linux_amd64
      - windows_amd64
      - darwin_amd64
      - darwin_arm64

archives:
  - formats: [ 'binary' ]

changelog:
  sort: asc
  filters:
    exclude:
      # - "^docs:"
      - "^test:"

announce:
  skip: .*

release:
  footer: >-

